dist: trusty
sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker pull truffle/ci

env:
  - TEST=native
  - TEST=repo
  - TEST=upstream
  - TEST=scenario

script:
  - npm run test:ci
